export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAILURE = 'GET_DETAILS_FAILURE';

export const GET_FILM_DETAILS_ASYNC = 'GET_FILM_DETAILS_ASYNC';
export const GET_PERSON_DETAILS_ASYNC = 'GET_PERSON_DETAILS_ASYNC';

export const RESET_DETAILS = 'RESET_DETAILS';
