export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_FAILURE = 'GET_FILMS_FAILURE';

export const GET_SIMILAR_FILMS_REQUEST = 'GET_SIMILAR_FILMS_REQUEST';
export const GET_SIMILAR_FILMS_SUCCESS = 'GET_SIMILAR_FILMS_SUCCESS';
export const GET_SIMILAR_FILMS_FAILURE = 'GET_SIMILAR_FILMS_FAILURE';