export const GET_FILM_DETAILS_ASYNC = 'GET_FILM_DETAILS_ASYNC';
export const GET_FILM_DETAILS_REQUEST = 'GET_FILM_DETAILS_REQUEST';
export const GET_FILM_DETAILS_SUCCESS = 'GET_FILM_DETAILS_SUCCESS';
export const GET_FILM_DETAILS_FAILURE = 'GET_FILM_DETAILS_FAILURE';
