export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';

export const GET_PEOPLE_ASYNC = 'GET_PEOPLE_ASYNC';
export const GET_FILMS_ASYNC = 'GET_LIST_ASYNC';
export const GET_FILMS_WITH_CAST_ASYNC = 'GET_FILMS_WITH_CAST_ASYNC';
export const GET_SIMILAR_FILMS_ASYNC = 'GET_SIMILAR_FILMS_ASYNC';

export const RESET_LIST = 'RESET_LIST';
