export const GET_MOVIECREDITS_ASYNC = 'GET_MOVIECREDITS_ASYNC';
export const GET_MOVIECREDITS_REQUEST = 'GET_MOVIECREDITS_REQUEST';
export const GET_MOVIECREDITS_SUCCESS = 'GET_MOVIECREDITS_SUCCESS';
export const GET_MOVIECREDITS_FAILURE = 'GET_MOVIECREDITS_FAILURE';
