export const GET_PERSON_DETAILS_ASYNC = 'GET_PERSON_DETAILS_ASYNC';
export const GET_PERSON_DETAILS_REQUEST = 'GET_PERSON_DETAILS_REQUEST';
export const GET_PERSON_DETAILS_SUCCESS = 'GET_PERSON_DETAILS_SUCCESS';
export const GET_PERSON_DETAILS_FAILURE = 'GET_PERSON_DETAILS_FAILURE';
