export default {
  GET_DETAILS_REQUEST: 'GET_DETAILS_REQUEST',
  GET_DETAILS_SUCCESS: 'GET_DETAILS_SUCCESS',
  GET_DETAILS_FAILURE: 'GET_DETAILS_FAILURE',

  GET_FILM_DETAILS_ASYNC: 'GET_FILM_DETAILS_ASYNC',
  GET_PERSON_DETAILS_ASYNC: 'GET_PERSON_DETAILS_ASYNC',

  RESET_DETAILS: 'RESET_DETAILS',
};
