export default {
  GET_LIST_REQUEST: 'GET_LIST_REQUEST',
  GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'GET_LIST_FAILURE',

  GET_PEOPLE_ASYNC: 'GET_PEOPLE_ASYNC',
  GET_FILMS_ASYNC: 'GET_LIST_ASYNC',
  GET_FILMS_WITH_CAST_ASYNC: 'GET_FILMS_WITH_CAST_ASYNC',
  GET_SIMILAR_FILMS_ASYNC: 'GET_SIMILAR_FILMS_ASYNC',

  RESET_LIST: 'RESET_LIST',
};
